### ISSUE TITLE
Is this formula working on Debian to distribute root cert?

### ISSUE THREAD

**Issue by daks** [saltstack-formulas/cert-formula#12]
Hello,

At the moment I use this formula to distribute cert+private key to servers needing it (web servers...) and that works.
But I wonder if this formula works on Debian to distribute public certificates (like custom CA certificate).

The formula put the cert in /etc/ssl/certs/ and run 'update-ca-certificates', but the normal workflow in Debian is to put the certificate in /usr/local/share/ca-certificates and then run 'update-ca-certificates' (see #7).

I have done some tests and I pretty sure it doesn't work for this usage.

I'm not sure if distribution of root certs is in the scope of this formula, but I think it is, and if not I think it should :)

Has anyone tried this use? Am I missing something?

**Comment by mthibaut** [comment]
You will need to change the formula to run `update-ca-certificates --fresh`. This is probably because the formula wasn't tested on Debian.

I'll probably upload a new formula forked from this one to do this soonish.

**Comment by javierbertoli** [comment]
@mthibaut, by this

> I'll probably upload a new formula forked from this one to do this soonish.

you mean a PR to this formula, right? It seems to be maintained, so I think it might be better to contrib to the maintainance of this one than adding a new formula?

**Comment by mthibaut** [comment]
Yes right, I meat a PR :). Just not sure if that is the right way. It looks like adding the key to `/etc/ca-certificates.conf` might be the "correct" way instead of using --fresh.

**Comment by javierbertoli** [comment]
awesome! :+1:

**Comment by ze42** [comment]
Considering the `update-ca-certificates` is only called on Debian, I take it has been tested on Debian.

One of the latest merge might be doing the trick, by having the proper file name (`xxx.crt`) might help.

**Comment by daks** [comment]
Quoting /usr/share/doc/ca-certificates/README.Debian from buster:

> How to install local CA certificates
> ------------------------------------------------------------------
>
> If you want to install local certificate authorities to be implicitly
> trusted, please put the certificate files as single files ending with
> ".crt" into /usr/local/share/ca-certificates/ and re-run
> 'update-ca-certificates'.  If you remove local certificates from
> /usr/local/share/ca-certificates/, you can remove symlinks by running
> 'update-ca-certificates --fresh'.  If you want to prepare a local
> package of your certificates, you should depend on ca-certificates,
> install the PEM files into /usr/local/share/ca-certificates/ as above
> and call 'update-ca-certificates' in the package's postinst, and should
> call 'update-ca-certificates --fresh' in the package's postrm.

**Comment by ameneau** [comment]
@daks The combination of #16 and #17 should resolve this issue. In #16, the .crt extension gets appended to certificate files being added to a system. In #17, the default certificate directory for debian family OSes is now /usr/local/share/ca-certificates

The kitchen-salt tests verify that the certificates make it into the master certificate store located in /etc/ssl/certs/ca-certificates.crt.

I think this can be closed?

**Comment by daks** [comment]
I'm actually evaluating the change and if it answers my needs, but I first need to adapt our current Salt code, because the change is not backward compatible *(which surprised me a bit)*.

**Comment by ameneau** [comment]
@daks There's only one (maybe two) change that makes this not backwards compatible. The ".crt" extension gets appended to the file name in #16. The reason I felt this change was acceptable is because key files get the .key extension appended to the end of the file name.

Although, now that I think about it, the change shouldn't prevent the certificate from being installed properly, you just might end up with ".crt.crt" as the filename suffix.

The only other potential point of confusion would be that the default certificate directory on Debian family OSes is now /usr/local/share/ca-certificates/ instead of being /etc/ssl/certs

I may have missed something important, if you discover an issue, please do let me know. I'll be happy to make changes.

Thanks!

**Comment by daks** [comment]
Moving the cert to a .crt extension is in fact logical, having the certificate without extension always seems weird to me :)

I see three changes in reality:
- on Debian, certs are directly stored in /usr/local/share/ca-certificates
- they are named with .crt extension
- the symlink in /etc/ssl/certs is named with .pem extension

Changes in our code was quite easy but I'm struggling with a 
```
  - watch:
    - file: /usr/local/share/ca-certificates/<cert>.crt
```
which don't validate in Salt, and I don't understand why.

I still need to evaluate what is the impact on our production servers (I think we'll need a special operation to remove the previous certificate stored without pem/crt extension) and if we can push a certificate (without key) with theses changes in the formula.

**Comment by daks** [comment]
I tested deploying a certificate without its key and it works fine. I close this issue. Thanks.
