### ISSUE TITLE
`test/salt/pillar/no_certs.sls` is currently unused

### ISSUE THREAD

**Issue by myii** [saltstack-formulas/cert-formula#29]
@daks Is there a plan for using this in a subsequent test suite?

**Comment by myii** [comment]
Was found during the process leading to #30.

**Comment by daks** [comment]
Not sure, it looks like it existed before implementing semantic-release and I forgot to remove it.

**Comment by myii** [comment]
@daks Shall I add it's removal to #30?

**Comment by daks** [comment]
yes, you can
