### ISSUE TITLE
Make public cert directory source configurable

### ISSUE THREAD

**Issue by herisanu** [saltstack-formulas/cert-formula#6]
Could we please make public cert directory on the saltmaster configurable or move it to salt://files/cert? [1]
The majority of the formulas store files under files/ directory.

[1] https://github.com/saltstack-formulas/cert-formula/blob/master/cert/init.sls#L31

**Comment by wwentland** [comment]
Why did you close this?

**Comment by herisanu** [comment]
Oh, sorry. I didn't comment this. I found a workable work-around.

My issue with the current setup was that there was no single rule as were to put my state file logic and `/srv/salt` was starting to have all kind of new directories which were there because of formulas I used (certs, files, salt etc.).

I ended up creating a `/srv/formulas/forumula-dependencies` folder where i would put all these files. This folder was added to file_roots.

The only lingering idea was that this formula should read the public keys from `cert/files` (or even pillar) to be more in line with other formulas. As this would break compatibility, I snuffed that idea out.

**Comment by wwentland** [comment]
I still like the idea of making this configurable though.

**Comment by daks** [comment]
@herisanu @babilen this issue can be closed now

**Comment by wwentland** [comment]
Ta!
